// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Location struct {
	Type        string    `json:"type"`
	Coordinates []float64 `json:"coordinates"`
}

type NewPhoto struct {
	URL    string `json:"url"`
	Lat    string `json:"lat"`
	Long   string `json:"long"`
	UserID string `json:"userId"`
}

type Photo struct {
	ID       string    `json:"id" bson:"_id,omitempty"`
	URL      string    `json:"url"`
	Location *Location `json:"location"`
	User     *User     `json:"user"`
}

type User struct {
	ID       string `json:"id" bson:"_id,omitempty"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserRegistration struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Jwt      string `json:"jwt"`
}
