// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPhoto struct {
	URL    string `json:"url"`
	Lat    string `json:"lat"`
	Long   string `json:"long"`
	UserID string `json:"userId"`
}

type Photo struct {
	ID   string `json:"id"`
	URL  string `json:"url"`
	Lat  string `json:"lat"`
	Long string `json:"long"`
	User *User  `json:"user"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
}
